FTP_HOST: str = "ftp.serwer.com"
FTP_USER: str = "USER"
FTP_PASSWORD: str = "PASSWORD"
EMAIL_SUBJECT: str = "SUBJECT"
EMAIL_FROM: str = "automat@email.com"
EMAIL_TO: str = "send_to@email.com"
EMAIL_SMTP: str = "IP"
FILE_PATH: str = "/volume1/folder/"
